config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'

  # resources :shops
  get '/allProduct', to: 'products#all_product'
  get '/addProduct', to: 'products#add_product'
  get '/editProduct', to: 'products#edit_product'

  post '/create_product', to: 'products#create_product', as: 'create_product'
  post '/increase_count', to: 'products#increase_count', as: 'increase_count'
  patch '/update_product', to: 'products#update_product', as: 'update_product'


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :collections
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    include ApplicationHelper

    def all_product
        session = ShopifyAPI::Auth::Session.new(
            shop: 'entry-try-shop.myshopify.com',
            access_token: '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'
        )

        query = <<~GQL
        {
            products(first: 10) {
               pageInfo {
                 hasNextPage
               }
               edges {
                 cursor
                 node {
                   id
                   title
                   handle
                   description
                   priceRange {
                     minVariantPrice {
                       amount
                       currencyCode
                     }
                     maxVariantPrice {
                       amount
                       currencyCode
                     }
                   }
                   images(first: 1) {
                     edges {
                       node {
                         src
                       }
                     }
                   }
                 }
               }
            }
           }
        GQL
        client = ShopifyAPI::Clients::Graphql::Admin.new(
            session: session
        )

        response = client.query(query: query)

        puts response.body.inspect
        @products= response.body["data"]["products"]["edges"]
        # binding.pry
        # shopify_service = ShopifyService.new
        # shop_data = shopify_service.get_shop_data
        # render json: shop_data
    end

    def add_product
      @categories = [
        'Clothing',
        'Shoes',
        'Accessories',
        'Bags',
        'Jewelry',
        'Watches',
        'Electronics',
        'Computers & Accessories',
        'Cell Phones & Accessories',
        'Camera & Photo',
        'Home & Kitchen',
        'Furniture',
        'Home Décor',
        'Bedding & Bath',
        'Kitchen & Dining',
        'Appliances',
        'Toys & Games',
        'Baby & Toddler',
        'Sports & Outdoors',
        'Exercise & Fitness',
        'Outdoor Recreation',
        'Team Sports',
        'Camping & Hiking',
        'Books',
        'Health & Household',
        'Vitamins & Dietary Supplements',
        'Personal Care',
        'Beauty',
        'Pet Supplies',
        'Automotive',
        'Industrial & Scientific',
        'Grocery & Gourmet Food',
        'Pet Supplies',
        'Handmade',
        'Others'
      ]

      session = ShopifyAPI::Auth::Session.new(
        shop: 'entry-try-shop.myshopify.com',
        access_token: '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'
    )

    query = <<~GQL
    {
      collections(first: 100) {
        nodes {
          id
          title
        }
      }
    }
    GQL

    client = ShopifyAPI::Clients::Graphql::Admin.new(
      session: session
  )
    
    @collections = client.query(query: query).body["data"]["collections"]["nodes"]
    end

    def create_product
        product_category = params[:category]
        product_collection = params[:collections]
        product_title = params[:productTitle]
        product_description = params[:productDescription]
        product_price = params[:productPrice]
        product_variant_number = params[:count].to_i
        product_media = params[:files].present? ? params[:files] : nil
        product_options = params[:productOptions].present? ? process_options(params[:productOptions]) : nil
        product_tags = params[:productTags].present? ? process_options(params[:productTags]) : nil

        
        
        session = ShopifyAPI::Auth::Session.new(
          shop: 'entry-try-shop.myshopify.com',
          access_token: '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'
      )
      client = ShopifyAPI::Clients::Graphql::Admin.new(
        session: session
    )
      
        # mutation = <<-GQL
        #   mutation {
        #     productCreate(input: {
        #       title: "#{product_title}",
        #       descriptionHtml: "#{product_description}",
        #       productType: "#{product_category}",
        #       variants: {
        #         price: "#{product_price}"
        #       }
        #     }) {
        #       product {
        #         id
        #         title
        #       }
        #       userErrors {
        #         field
        #         message
        #       }
        #     }
        #   }
        # GQL

        media_array = []
        options_array = []
        tags_array = []
        variant_array = []

        if product_variant_number > 0
          product_variant_number.times do |i|
            data = {
              "title":  params["variant_#{i+1}_title"],
              "price": params["variant_#{i+1}_price"],
              "options": process_options(params["variant_#{i+1}_options"])
            }

            variant_array << data
          end

        end

        if product_media.present?
          product_media.each do |file, index|
            # Access the file and content-type from here
            # puts content_type = file.content_type
            # puts file_object = file.tempfile.open

            data = {
              "alt": file.original_filename,
              "mediaContentType": "IMAGE",
              # "originalSource": file.tempfile.open
              "originalSource": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgpJGuO4BZFBQF1_vfJtpiYBQxNR6Ud_oRHaOGy8H7&s"
            }

            media_array << data
          
            # Perform operations on the file as per your requirement
            # ...
          end
        end


        # product_options.each do |key, value|
        #   options_array << value
        # end

        # product_tags.each do |key, value|
        #   tags_array << value
        # end



        query = <<~QUERY
        mutation productCreate($input: ProductInput!) {
          productCreate(input: $input) {
            product {
              id
              title
            }
            userErrors {
              field
              message
            }
          }
        }        
        QUERY
        variables = {
          "input": {
            "collectionsToJoin": product_collection,
            "descriptionHtml": "#{product_description}",
            "productType": "#{product_category}",
            "published": true,
            "redirectNewHandle": true,
            "requiresSellingPlan": true,
            # "seo": {
            #   "description": "",
            #   "title": ""
            # },
            "options": product_options,
            "tags": product_tags,            
            "title": "#{product_title}",
            "variants": variant_array
            # [
            #   {
                # "barcode": "",
                # "compareAtPrice": "",
                # "fulfillmentServiceId": "",
                # "harmonizedSystemCode": "",
                # "id": "",
                # "imageId": "",
                # "imageSrc": "",
                # "inventoryItem": {
                #   "cost": "",
                #   "tracked": true
                # },
                # "inventoryManagement": "",
                # "inventoryPolicy": "",
                # "inventoryQuantities": [
                #   {
                #     "availableQuantity": 1,
                #     "locationId": ""
                #   }
                # ],
                # "mediaId": "",
                # "mediaSrc": [
                #   ""
                # ],
                # "metafields": [
                #   {
                #     "description": "",
                #     "id": "",
                #     "key": "",
                #     "namespace": "",
                #     "type": "",
                #     "value": ""
                #   }
                # ],
                # "options": [
                #   ""
                # ],
                # "position": 1,
                # "price": "#{product_price}",
                # "requiresComponents": false,
                # "requiresShipping": true,
                # "taxable": true,
                # "weight": 1.1,
                # "weightUnit": ""
            #   }
            # ]
          },
          "media": media_array
        }
        
      
       
          
        # @collections = client.query(query: query).body["data"]["collections"]["nodes"]
        response = client.query(query: query, variables: variables)

        # puts response.inspect

        # if response.present? && response.body['data']['productCreate'].present? && response.body['data']['productCreate']['product'].present?
          
          # query = <<~QUERY
          #   mutation collectionAddProducts($id: ID!, $productIds: [ID!]!) {
          #     collectionAddProducts(id: $id, productIds: $productIds) {
          #       collection {
          #         id
          #         title
          #         productsCount
          #         products(first: 10) {
          #           nodes {
          #             id
          #             title
          #           }
          #         }
          #       }
          #       userErrors {
          #         field
          #         message
          #       }
          #     }
          #   }
          # QUERY
          # variables = {
          #   "id": "#{product_collection}",
          #   "productIds": ["#{response.body['data']['productCreate']['product']["id"]}"]
          # }
          # addedCollection = client.query(query: query, variables: variables)


          # puts addedCollection.inspect

          # redirect_to root_path
          # flash[:notice] = 'Product was successfully added.'

        # else
        #   redirect_to addProduct_path
        #   flash[:alert] = 'Failed to add product.'
        # end

        puts product_category
        puts product_collection
        puts product_title
        puts product_description
        puts product_price

app/views/products/_form_variant.html.erb
  <%
=begin%>
 <% if @count > 0 %>

    <% @count.times do |i| %>
      <%= label_tag "variant_#{i+1}_title", "Variant #{i+1} Title" %>
      <%= text_field_tag "variant_#{i+1}_title" %><br>
      <%= label_tag "variant_#{i+1}_price", "Variant #{i+1} Price" %>
      <%= text_field_tag "variant_#{i}_price" %><br>
    <% end %>

  <% end %> 
<%
=end%>

app/views/products/add_product.html.erb
<h1>Add product</h1>

<h3>
If you want to add extra features than selecct one
</h3>
<div class="d-flex gap-3">
  <%= custom_property_button("media", "toggle-button") %>
  <%= custom_property_button("options", "toggle-button") %>
  <%= custom_property_button("tags", "toggle-button") %>
  <%= custom_property_button("add_variant","bg-primary text-white add_variant") %>
  <%
=begin%>
 <%= button_to 'Add Variant', increase_count_path %>
  <%= button_to 'Add Variant', { action: "increase_count" }, method: :post, remote: true %> 
<%
=end%>
</div>

<div class="container mt-5">
  <%= form_tag create_product_path,id:"add_product", multipart: true, method: :post do %>

  <%= category_form_field("category", "categories", @categories) %>

  <%
=begin%>
 <%= category_form_field("collection", "collections", @collections) %> 
<%
=end%>
  
  <%= multiple_select("collection", "collections", @collections) %>

  <%= custom_div_with_label_and_input_class('proTitle', 'Product Title', 'productTitle', 'form-control') %>
  
  <%= custom_div_with_label_and_input_class('proDesc', 'Product Description', 'productDescription', 'form-control') %>

  <%= custom_div_with_label_and_input_class('proPrice', 'Product Price', 'productPrice', 'form-control') %>

  <%= custom_div_with_label_and_input_class('options','Product Options', 'productOptions', 'form-control','d-none', true) %>

  <%= custom_div_with_label_and_input_class('tags','Product Tags', 'productTags', 'form-control','d-none', true) %>

  <%= text_field_tag("count", nil, class: "count", type: "hidden", value: "0") %>
 
  <%
=begin%>
 <%= select_tag 'Collections', options_for_select(@collections.map { |collection| ["#{collection["title"]}", "#{collection["id"]}"] }, @selected_country), {include_blank: true, multiple: true, class: "from-control"} %>  
<%
=end%>
  <%
=begin%>
 <%= select_tag 'Collections', collection_check_boxes(@collections, :post, @collections, "id", "title", options = {}, html_options = {}), {include_blank: true, multiple: true, class: "from-control"} %>  
<%
=end%>




  <div class="form-group d-none" id="media">
    <%= label_tag :files, 'Product Media' %>
    <%= file_field_tag 'files[]', multiple: true, class:"form-control" %>
  </div>
  <%= submit_tag 'Add Product', class: 'btn btn-primary mt-4' %>
<% end %>

</div>

<%= javascript_include_tag 'custom' %>

app/views/products/all_product.html.erb
<h1>All product List of your development store</h1>

<% @products.each do |product| %>
    <p><%= product["node"]["title"] %></p>
<% end %>

app/views/products/edit_product.html.erb
<h1> Edit product</h1>

<div class="d-flex justify-content-center ">
<%= form_tag editProduct_path, method: :patch do %>
    <div class="form-group text-center">
      <%= label_tag 'productId', 'Select a product' %>
      
    </div>
    <%= submit_tag 'Select a Product', class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="container mt-5">
  <%= form_tag update_product_path, method: :patch do %>
    <div class="form-group d-none">
      <%= label_tag 'productId', 'Product ID' %>
      <%= text_field_tag 'productId', nil, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= label_tag 'productPrice', 'New Product Price' %>
      <%= text_field_tag 'productPrice', nil, class: 'form-control', required: true %>
    </div>
    <%= submit_tag 'Update Product', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/products/index.html.erb
<h1>All product List of your development store</h1>

<% @products.each do |product| %>
    <p><%= product["node"]["title"] %></p>
<% end %>